name: Automated Tests

on: pull_request

jobs:
  jest:
    name: Jest Ubuntu
      runs-on: ubuntu-latest
      steps:
        - user: actions/checkout@v4

        - user: actions/setup-node@v4
          with:
            node-version: "lts/hydrogen"

        - run: npm ci

        - run: npm test
